### PR TITLE
Added more logging and an exception printer!

### PR DESCRIPTION
**Pull request by XavilPergis**
### Overview

Adds more logging, cleans up logger.py, and adds a `logger.print_excption()` function

### List of changes

  1. More logging and fixed severity levels
  2. Makes code in logger.py more readable
  3. Adds a `logger.print_excption()` to prettyprint the last exception
  4. Moves settings/colors.py to core/colors.py

### CODE REVIEW

**Comment by surrsurus** [comment]
Looks like a lot of good changes here. Just watch out though because in the latest master, some of the logging becomes redundant because I got to some of those already. Otherwise, all of your changes look good.

**Comment by XavilPergis** [comment]
The logger.py file should work as a standalone :D

**Comment by XavilPergis** [comment]
This request is too far behind the other branches, so I'm closing it.

**Comment by surrsurus** [comment]
Can you reopen this issue? These contributions are really good.

**Comment by surrsurus** [comment]
Perhaps bring the files up to date with master or testing and implement them. I'm not going to be committing for a little bit.

**Comment by XavilPergis** [comment]
Sure, in a little bit :)

**Pull request closed without merging**
